### ISSUE TITLE
Version '70.0.3538.102-1' for 'google-chrome-stable' was not found

### ISSUE THREAD

**Issue by cypna** [pinkeen/docker-html-to-pdf#4]
i m getting while building docker

**Comment by pinkeen** [comment]
Hello, thanks for reporting the issue.

The package seems to be gone from the upstream repository. I have bumped chrome to v74. The latest version should build. As always the new version is tagged as `74.0` in git and uses `:74` tag in docker hub.

Please note that you also can use the binary image from docker hub instead of building yourself.

Fixed by 0daa9f58debe6dc65f97d254eccf9491f9ea6d62
